import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, relative, resolve, sep } from "node:path";
import { CliError, type Ctx, exec, print, type RunResult, which } from "./lib";
import { ENGINE, importGraph, sdlLibrary, stageGame, vendorFix, vendorStatus } from "./native";

export interface IosTarget {
  platform: "ios";
  // Entry module exporting init(base: string): void and frame(time: number): boolean (see the ios skill).
  entry: string;
  bundleId: string;
  team: string;
  // PNG, any size; scaled to the 1024 px App Store icon.
  icon?: string;
  orientation?: "landscape" | "portrait";
  // Folder bundled under <app>/game/<assets>; the engine fonts go under <app>/game/dotframe/assets/fonts.
  assets?: string;
  // Home screen name; defaults to the game name.
  displayName?: string;
}

const SKILL = "ios";

async function scriptcVersion(ctx: Ctx, root: string): Promise<string> {
  const r = await exec({ ...ctx, json: true }, root, { label: "scriptc version", argv: ["scriptc", "--version"] });
  return r.output.trim();
}

// scriptc's iOS runtime pack must match the compiler. Looked up in the game, the engine, then ~/.dotframe/scriptc-ios.
export async function iosRuntimePack(ctx: Ctx, root: string): Promise<{ path: string | null; want: string; found: string | null }> {
  const want = await scriptcVersion(ctx, root);
  const dirs = [root, ENGINE, join(homedir(), ".dotframe", "scriptc-ios")];
  for (const dir of dirs) {
    const pack = join(dir, "node_modules", "@scriptc", "runtime-ios-arm64");
    if (!existsSync(join(pack, "package.json"))) continue;
    const found = (JSON.parse(await Bun.file(join(pack, "package.json")).text()) as { version: string }).version;
    return { path: found === want ? pack : null, want, found };
  }
  return { path: null, want, found: null };
}

export function iosPackFix(want: string): string {
  // Fresh scriptc releases trip bun's minimum release age for a couple of days.
  return `mkdir -p ~/.dotframe/scriptc-ios && cd ~/.dotframe/scriptc-ios && bun add @scriptc/runtime-ios-arm64@${want} --minimum-release-age 0`;
}

function identifier(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "") || "game";
}

function scheme(name: string): string {
  return name.split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("") || "Game";
}

function hostC(id: string, display: string): string {
  return `// iOS host for ${display}, generated by dotframe build ios. SDL3 owns the app lifecycle through main callbacks
// and drives the scriptc library: init once with the bundle's game folder, then frame per display refresh.
#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <stdint.h>
#include <string.h>

void ${id}_runtime_init(void);
int32_t ${id}_register_callbacks(void);
void ${id}_init(const uint8_t *base, int64_t base_len);
uint8_t ${id}_frame(double time);
void df_handle_event(const SDL_Event *event);
void df_close(void);

static Uint64 g_start;

SDL_AppResult SDL_AppInit(void **appstate, int argc, char **argv) {
  (void)appstate;
  (void)argc;
  (void)argv;
  ${id}_runtime_init();
  int32_t failed = ${id}_register_callbacks();
  if (failed != 0) {
    SDL_Log("${id}: %d callbacks failed to register", failed);
    return SDL_APP_FAILURE;
  }
  const char *bundle = SDL_GetBasePath();
  if (!bundle) return SDL_APP_FAILURE;
  char base[4096];
  SDL_snprintf(base, sizeof base, "%sgame", bundle);
  ${id}_init((const uint8_t *)base, (int64_t)strlen(base));
  g_start = SDL_GetTicksNS();
  return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void *appstate) {
  (void)appstate;
  double time = (double)(SDL_GetTicksNS() - g_start) / 1e9;
  return ${id}_frame(time) ? SDL_APP_CONTINUE : SDL_APP_SUCCESS;
}

SDL_AppResult SDL_AppEvent(void *appstate, SDL_Event *event) {
  (void)appstate;
  df_handle_event(event);
  return event->type == SDL_EVENT_QUIT ? SDL_APP_SUCCESS : SDL_APP_CONTINUE;
}

void SDL_AppQuit(void *appstate, SDL_AppResult result) {
  (void)appstate;
  (void)result;
  df_close();
}

// scriptc library mode references the promise runtime from bytes IO but ships none; library mode has no async.
void scr_promise_settled_ref(void) { SDL_assert_always(!"scriptc promise in library mode"); }
void scr_promise_settled_void(void) { SDL_assert_always(!"scriptc promise in library mode"); }
`;
}

function infoPlist(display: string, orientation: "landscape" | "portrait"): string {
  const orientations =
    orientation === "portrait"
      ? ["UIInterfaceOrientationPortrait"]
      : ["UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDisplayName</key><string>${display}</string>
  <key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleName</key><string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSRequiresIPhoneOS</key><true/>
  <key>UIRequiresFullScreen</key><true/>
  <key>UIStatusBarHidden</key><true/>
  <key>UIViewControllerBasedStatusBarAppearance</key><false/>
  <key>UILaunchScreen</key><dict/>
  <key>UISupportedInterfaceOrientations</key>
  <array>
${orientations.map((o) => `    <string>${o}</string>`).join("\n")}
  </array>
</dict>
</plist>
`;
}

function projectYml(o: { name: string; id: string; bundleId: string; team: string; vendor: string; sdl: string; lib: string; icon: boolean }): string {
  const frameworks = ["UIKit", "Foundation", "Metal", "QuartzCore", "AVFoundation", "AudioToolbox", "CoreAudio", "CoreBluetooth", "CoreGraphics", "CoreHaptics", "CoreMotion", "GameController", "IOSurface", "UniformTypeIdentifiers", "CoreMedia", "CoreVideo", "OpenGLES"];
  return `name: ${o.name}
options:
  deploymentTarget:
    iOS: "17.0"
targets:
  ${o.name}:
    type: application
    platform: iOS
    sources:
      - path: host/main.c
      - path: ${o.id}_glue.c
      - path: ${join(ENGINE, "native", "df_native.c")}
      - path: ${join(ENGINE, "native", "df_audio.c")}
      - path: ${join(ENGINE, "native", "df_ws_apple.m")}
      - path: game
        type: folder
        buildPhase: resources
${o.icon ? "      - path: Assets.xcassets\n" : ""}    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${o.bundleId}
        DEVELOPMENT_TEAM: ${o.team}
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: host/Info.plist
${o.icon ? "        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon\n" : ""}        TARGETED_DEVICE_FAMILY: "1,2"
        HEADER_SEARCH_PATHS:
          - ${join(o.vendor, o.sdl, "include")}
          - ${join(o.vendor, "wgpu", "ios", "include")}
          - ${join(ENGINE, "native")}
        OTHER_LDFLAGS:
          - ${o.lib}
          - ${join(o.vendor, sdlLibrary("ios"))}
          - ${join(o.vendor, "wgpu", "ios", "lib", "libwgpu_native.a")}
          - -lc++
          - -liconv
        CLANG_ENABLE_OBJC_ARC: YES
        GCC_WARN_INHIBIT_ALL_WARNINGS: YES
        ENABLE_BITCODE: NO
    dependencies:
${frameworks.map((f) => `      - sdk: ${f}.framework`).join("\n")}
`;
}

// check: stop after the scriptc library (library mode is stricter than an executable build), for doctor.
// The df* host functions the code reachable from the entry calls (engine files included, since staged imports are
// relative): only those become library callbacks, because scriptc caps them at 32.
function usedHostFunctions(entry: string): string[] {
  const used = new Set<string>();
  for (const file of importGraph(entry).files) {
    if (!file.endsWith(".ts") || file.endsWith(`${sep}ffi.ts`)) continue;
    for (const m of readFileSync(file, "utf8").matchAll(/\b(df[A-Z]\w*)\(/g)) used.add(m[1]);
  }
  return [...used].sort();
}

export async function buildIos(ctx: Ctx, root: string, gameName: string, targetName: string, t: IosTarget, check = false): Promise<{ app: string; log: string; steps: RunResult[] }> {
  for (const tool of check ? ["scriptc"] : ["scriptc", "xcodegen", "xcodebuild", "sips"]) {
    if (!which(tool)) throw new CliError("TOOL_MISSING", `${tool} not found`, tool === "xcodegen" ? "brew install xcodegen" : tool === "scriptc" ? "npm i -g scriptc" : "install Xcode", SKILL);
  }
  for (const key of ["entry", "bundleId", "team"] as const) {
    if (!t[key]) throw new CliError("BAD_CONFIG", `targets.${targetName}.native.${key} is required for iOS`, `dotframe config set targets.${targetName}.native.${key} '"..."'`, SKILL);
  }
  if (!existsSync(join(root, t.entry))) throw new CliError("ENTRY_MISSING", `iOS entry ${t.entry} does not exist`, "add it (see the ios skill: export init and frame)", SKILL);
  const vendor = vendorStatus("ios");
  if (vendor.missing.length > 0 && !check) throw new CliError("VENDOR_MISSING", `iOS needs SDL3 and wgpu-native in ${vendor.dir}; missing ${vendor.missing.join(", ")}`, vendorFix("ios"), SKILL);
  const pack = await iosRuntimePack(ctx, root);
  if (!pack.path) {
    throw new CliError("TOOL_MISSING", pack.found ? `scriptc iOS runtime pack is ${pack.found}, scriptc is ${pack.want}` : `scriptc iOS runtime pack ${pack.want} not found`, iosPackFix(pack.want), SKILL);
  }

  const display = t.displayName ?? gameName;
  const id = identifier(gameName);
  const name = scheme(display);
  const stage = join(root, ".dotframe", check ? "check" : "native", targetName);
  const out = join(root, "dist", targetName);
  const app = join(out, `${name}.app`);
  const logDir = join(root, ".dotframe", "logs");
  const log = join(logDir, `${check ? "check" : "build"}-${targetName}.log`);
  if (ctx.dryRun) {
    print(ctx, { dryRun: true, platform: "ios", stage, app, scheme: name, bundleId: t.bundleId, team: t.team, runtimePack: pack.path }, (): string => `would stage ${t.entry} in ${stage} and build ${app}`);
    return { app, log, steps: [] };
  }
  rmSync(stage, { recursive: true, force: true });
  mkdirSync(join(stage, "host"), { recursive: true });
  mkdirSync(logDir, { recursive: true });
  const engineStage = join(stage, "dotframe");
  cpSync(join(ENGINE, "src"), join(engineStage, "src"), { recursive: true });
  const gameStage = stageGame(root, t.entry, join(stage, "tree"), engineStage);
  // A throw in library mode becomes a trap that aborts with no message (SIGABRT in SDL_AppInit). The wrapper prints
  // the error and its stack to stderr, which the device log keeps, before rethrowing.
  const wrapper = join(gameStage, "dotframe-entry.ts");
  const gameEntry = `./${t.entry.replace(/\.ts$/, "")}`;
  writeFileSync(
    wrapper,
    `import { frame as gameFrame, init as gameInit } from ${JSON.stringify(gameEntry)};

function report(where: string, error: unknown): void {
  const detail = error instanceof Error ? \`\${error.message}\\n\${error.stack ?? ""}\` : String(error);
  console.error(\`dotframe: \${where} threw: \${detail}\`);
}

export function init(base: string): void {
  try {
    gameInit(base);
  } catch (error) {
    report("init", error);
    throw error;
  }
}

export function frame(time: number): boolean {
  try {
    return gameFrame(time);
  } catch (error) {
    report("frame", error);
    throw error;
  }
}
`,
  );
  writeFileSync(
    join(stage, "app.json"),
    JSON.stringify({ name: id, entry: relative(stage, wrapper), exports: [{ export: "init", params: ["string"], returns: "void" }, { export: "frame", params: ["f64"], returns: "bool" }] }, null, 2),
  );
  writeFileSync(join(stage, "host", "main.c"), hostC(id, display));
  writeFileSync(join(stage, "host", "Info.plist"), infoPlist(display, t.orientation ?? "landscape"));
  // Bundle resources: the game's assets and the engine fonts, under <app>/game.
  const bundle = join(stage, "game");
  mkdirSync(bundle, { recursive: true });
  const assets = t.assets ?? "assets";
  if (existsSync(join(root, assets))) cpSync(join(root, assets), join(bundle, assets), { recursive: true });
  cpSync(join(ENGINE, "assets", "fonts"), join(bundle, "dotframe", "assets", "fonts"), { recursive: true });

  const steps: { label: string; argv: string[]; cwd?: string; env?: Record<string, string> }[] = [];
  if (t.icon && !check) {
    const icons = join(stage, "Assets.xcassets", "AppIcon.appiconset");
    mkdirSync(icons, { recursive: true });
    writeFileSync(join(stage, "Assets.xcassets", "Contents.json"), '{"info":{"author":"xcode","version":1}}\n');
    writeFileSync(join(icons, "Contents.json"), '{"images":[{"filename":"icon-1024.png","idiom":"universal","platform":"ios","size":"1024x1024"}],"info":{"author":"xcode","version":1}}\n');
    steps.push({ label: "icon", argv: ["sips", "-z", "1024", "1024", resolve(root, t.icon), "--out", join(icons, "icon-1024.png")] });
  }
  steps.push(
    { label: "library glue", argv: ["bun", join(ENGINE, "tools", "gen-library-glue.ts"), join(stage, "app.json"), stage, join(ENGINE, "native", "ffi.macos.json"), usedHostFunctions(wrapper).join(",")] },
    { label: "scriptc library", argv: ["scriptc", "build", "--lib", "--profile", `${id}.profile.json`], cwd: stage, env: { SCRIPTC_TARGET: "aarch64-apple-ios", SCRIPTC_RUNTIME_PACK: pack.path } },
  );
  const results: RunResult[] = [];
  const full: string[] = [];
  const run = async (step: { label: string; argv: string[]; cwd?: string; env?: Record<string, string> }): Promise<void> => {
    if (!ctx.json) console.error(`> ${step.label}`);
    const r = await exec(ctx, root, step);
    full.push(`> ${step.label}: ${step.argv.join(" ")}\n${r.output}`);
    writeFileSync(log, full.join("\n"));
    results.push(r);
    if (r.code !== 0) {
      const count = r.output.match(/(\d+) errors?/)?.[1];
      throw new CliError("STEP_FAILED", `step "${step.label}" exited ${r.code}${count ? ` with ${count} errors` : ""}; full output in ${log}\n${r.tail}`, `read ${log}`, SKILL, 1, log);
    }
  };
  for (const step of steps) await run(step);
  if (check) return { app, log, steps: results };
  const lib = readdirSync(join(stage, ".scriptc")).find((f: string): boolean => f.endsWith(".lib.a"));
  if (!lib) throw new CliError("STEP_FAILED", "scriptc produced no .lib.a", `read ${log}`, SKILL, 1, log);
  writeFileSync(join(stage, "project.yml"), projectYml({ name, id, bundleId: t.bundleId, team: t.team, vendor: vendor.dir, sdl: vendor.sdl ?? "", lib: join(stage, ".scriptc", lib), icon: !!t.icon }));
  await run({ label: "xcodegen", argv: ["xcodegen", "generate"], cwd: stage });
  await run({ label: "xcodebuild", argv: ["xcodebuild", "-scheme", name, "-destination", "generic/platform=iOS", "-allowProvisioningUpdates", "-derivedDataPath", join(stage, "derived"), "build", "-quiet"], cwd: stage });
  const built = join(stage, "derived", "Build", "Products", "Debug-iphoneos", `${name}.app`);
  if (!existsSync(built)) throw new CliError("STEP_FAILED", `xcodebuild finished but ${built} is missing`, `read ${log}`, SKILL, 1, log);
  rmSync(app, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });
  cpSync(built, app, { recursive: true });
  return { app, log, steps: results };
}
