import { cpSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { CliError, type Config, type Ctx, exec, which } from "./lib";
import { ENGINE, stageGame } from "./native";

export interface NativeReplay {
  file: string;
  seed: number;
  options: Record<string, unknown>;
  inputs: { frame: number; inputs: number[] }[];
  frames: number;
  throughOver: boolean;
  checksums: { frame: number; checksum: number }[];
  final: number;
}

export interface NativeResult {
  file: string;
  ok: boolean;
  firstMismatch: number | null;
  expected: number;
  got: number;
  error?: string;
}

// The JS replays run on Bun; the shipped game runs compiled by scriptc, which rejects some code Bun accepts (a
// value outside a declared union, for one) and aborts at run time. This compiles the game's sim with scriptc, with
// every replay's options inlined and its inputs and checksums in a data file next to it, and runs it headless, so a native-only crash or divergence shows up off the device.
export async function verifyNative(ctx: Ctx, config: Config, replays: NativeReplay[]): Promise<NativeResult[]> {
  if (!which("scriptc")) throw new CliError("TOOL_MISSING", "scriptc not found", "npm i -g scriptc", "macos");
  if (!config.sim) throw new CliError("NO_SIM", `dotframe.json has no "sim" module`, `add "sim": "path/to/sim.ts"`, "core");
  const root = config.root;
  const work = join(root, ".dotframe", "replay-native");
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });
  // The entry sits in the game root so its import of the sim is relative, like main.native.ts.
  const entryName = ".dotframe-replay.native.ts";
  const entry = join(root, entryName);
  writeFileSync(entry, entrySource(`./${relative(root, join(root, config.sim)).replace(/\.tsx?$/, "")}`, replays));
  // Inputs and checksums go in plain text files, one per replay, read at run time: as one literal in the entry they
  // were most of the compile (a few dozen long replays made a 23 MB initializer; scriptc 0.2.7's codegen never
  // finished it).
  replays.forEach((r, i: number): void => {
    writeFileSync(join(work, `replay-${i}.inputs`), r.inputs.map((k) => [k.frame, ...k.inputs].join(" ")).join("\n"));
    writeFileSync(join(work, `replay-${i}.checks`), r.checksums.map((c) => `${c.frame} ${c.checksum}`).join("\n"));
  });
  try {
    const engineStage = join(work, "dotframe");
    cpSync(join(ENGINE, "src"), join(engineStage, "src"), { recursive: true });
    const gameStage = stageGame(root, entryName, join(work, "game"), engineStage);
    const binary = join(work, "replay");
    const built = await exec(ctx, root, { label: "scriptc", argv: ["scriptc", "build", entryName, "-o", binary], cwd: gameStage, env: {} });
    if (built.code !== 0) throw new CliError("STEP_FAILED", `scriptc could not compile the sim for native replays\n${built.tail}`, "fix the scriptc error; the native build hits the same one", "macos", 1);
    // One process per replay: an abort in one replay must not hide the others.
    return replays.map((r, i): NativeResult => {
      const ran = Bun.spawnSync([binary, join(work, `replay-${i}`), String(i)], { cwd: root, stdout: "pipe", stderr: "pipe" });
      const out = ran.stdout.toString();
      const done = out.match(/^DFREPLAY (-?\d+) (\d+)$/m);
      if (!done) {
        const reached = [...out.matchAll(/^DFFRAME (\d+)$/gm)].pop();
        const err = ran.stderr.toString().trim().split("\n").filter((l: string): boolean => l.trim() !== "");
        const at = reached ? Number(reached[1]) : 0;
        return { file: r.file, ok: false, firstMismatch: at, expected: r.final, got: 0, error: `aborted after frame ${at}: ${err.slice(-2).join(" ") || `exit ${ran.exitCode}`}` };
      }
      const mismatch = Number(done[1]);
      const got = Number(done[2]);
      return { file: r.file, ok: mismatch < 0 && got === r.final, firstMismatch: mismatch >= 0 ? mismatch : got === r.final ? null : r.frames, expected: r.final, got };
    });
  } finally {
    rmSync(entry, { force: true });
  }
}

function entrySource(simImport: string, replays: NativeReplay[]): string {
  const data = replays.map((r) => ({ seed: r.seed, options: r.options, frames: r.frames, throughOver: r.throughOver }));
  return `// Generated by dotframe replay verify --native; deleted after the run.
import { readFileSync } from "node:fs";
import type { Color, Draw, PipelineOptions, RenderGpu, Texture } from "dotframe/src/gpu";
import type { SimPlatform } from "dotframe/src/sim";
import sim from "${simImport}";

interface Keyed { frame: number; inputs: number[] }
interface Check { frame: number; checksum: number }
interface Data { seed: number; options: Record<string, unknown>; frames: number; throughOver: boolean }

// One line per entry, space-separated numbers.
function rows(path: string): number[][] {
  const text = readFileSync(path, "utf8");
  if (text === "") return [];
  return text.split("\\n").map((line: string): number[] => line.split(" ").map((v: string): number => Number(v)));
}

// Typed, with every field (mobile included) and no cast: scriptc builds records from the declared shape, and a
// cast-in stub with a field missing aborts at the first read of a neighboring optional field.
let nextTexture = 1;
const gpu: RenderGpu = {
  createBuffer: (_usage: number, _data: Uint8Array): number => 0,
  writeBuffer: (_buffer: number, _data: Uint8Array): void => {},
  destroyBuffer: (_buffer: number): void => {},
  createPipeline: (_options: PipelineOptions): number => 0,
  bind: (_pipeline: number, _buffer: number, _texture: number, _texture2?: number): number => 0,
  createTexture: (width: number, height: number, _rgba: Uint8Array, _smooth: boolean, _mipmaps?: boolean): Texture => ({ id: nextTexture++, width, height }),
  createTarget: (width: number, height: number): Texture => ({ id: nextTexture++, width, height }),
  destroyTexture: (_texture: Texture): void => {},
  frame: (_clear: Color, _draws: Draw[], _target?: Texture): void => {},
  aspect: (): number => 16 / 9,
  mobile: false,
};

const replays: Data[] = ${JSON.stringify(data)};

{
  const i = Number(process.argv[process.argv.length - 1]);
  const base = process.argv[process.argv.length - 2];
  const r = replays[i];
  const inputs: Keyed[] = rows(base + ".inputs").map((row: number[]): Keyed => ({ frame: row[0], inputs: row.slice(1) }));
  const checks: Check[] = rows(base + ".checks").map((row: number[]): Check => ({ frame: row[0], checksum: row[1] }));
  nextTexture = 1;
  // image is set though headless runs never load: scriptc 0.2.3 aborts reading an absent optional function field
  // through the contextually typed create(platform) parameter.
  const platform: SimPlatform = { gpu, load: async (_p: string): Promise<Uint8Array> => new Uint8Array(0), headless: true, image: async (_bytes: Uint8Array, _smooth: boolean, _mipmaps?: boolean): Promise<Texture> => ({ id: nextTexture++, width: 1, height: 1 }) };
  const run = sim.create(platform);
  run.start(r.seed, r.options);
  let cur: number[] = inputs.length > 0 ? inputs[0].inputs : [];
  let k = 0;
  let c = 0;
  let mismatch = -1;
  for (let f = 0; f < r.frames && (r.throughOver || !run.over()); f++) {
    while (k < inputs.length && inputs[k].frame <= f) {
      cur = inputs[k].inputs;
      k++;
    }
    run.step(cur);
    if ((f + 1) % 60 === 0) {
      console.log("DFFRAME " + String(f + 1));
      if (mismatch < 0 && c < checks.length && checks[c].checksum !== run.checksum()) mismatch = checks[c].frame;
      c++;
    }
  }
  console.log("DFREPLAY " + String(mismatch) + " " + String(run.checksum()));
}
`;
}
