import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import pkg from "../../package.json" with { type: "json" };
import { CliError, CONFIG_FILE, type Config, type Ctx, exec, formatJson, gate, loadConfig, print, target, which } from "../lib";

// Web plus relay as a docker compose stack (Dokploy builds it from the git repo): the game at / and the relay at
// /relay on the same host. Generated once by `deploy init`, then committed and edited like any other source.

const DIR = "deploy";

async function gitRoot(ctx: Ctx, root: string): Promise<string> {
  const r = await exec({ ...ctx, json: true }, root, { label: "git root", argv: ["git", "rev-parse", "--show-toplevel"] });
  if (r.code !== 0) throw new CliError("NOT_A_REPO", "Dokploy builds from a git repository, and this game is not in one", "git init, commit, and push to GitHub first", "export-web");
  return r.output.trim();
}

interface Versions {
  bun: string;
  dotframe: string;
}

// Pinned versions, so an image built tomorrow is the image built today: bun from packageManager (the game's
// package.json, then the repo root's), else the bun running this CLI; dotframe as installed in the game.
function versions(gameRoot: string, repo: string): Versions {
  let bun = Bun.version;
  for (const dir of [gameRoot, repo]) {
    const file = join(dir, "package.json");
    if (!existsSync(file)) continue;
    const manager = (JSON.parse(readFileSync(file, "utf8")) as { packageManager?: string }).packageManager ?? "";
    const match = manager.match(/^bun@(\d+\.\d+\.\d+)/);
    if (match) {
      bun = match[1];
      break;
    }
  }
  const installed = join(gameRoot, "node_modules", "dotframe", "package.json");
  const dotframe = existsSync(installed) ? (JSON.parse(readFileSync(installed, "utf8")) as { version: string }).version : pkg.version;
  return { bun, dotframe };
}

// game: the game's path inside the repo ("" at the root); context: the repo root, relative to deploy/.
// site: a static folder (relative to the game root) served at /, with the game at gamePath (for example "/play/").
interface Layout {
  site?: string;
  gamePath: string;
}

function files(config: Config, game: string, out: string, context: string, v: Versions, layout: Layout): Record<string, string> {
  const requires = (config.requires ?? []).filter((t: string): boolean => t !== "bun");
  const apt = requires.length > 0 ? `RUN apt-get update && apt-get install -y --no-install-recommends ${requires.join(" ")} && rm -rf /var/lib/apt/lists/*\n` : "";
  const at = game === "" ? "." : game;
  return {
    "Dockerfile.web": `# Static web build of ${config.name}, served by nginx. Generated by dotframe deploy init; edit freely.
FROM oven/bun:${v.bun} AS build
${apt}WORKDIR /app
COPY . .
RUN cd ${at} && bun install --frozen-lockfile && bun node_modules/dotframe/cli/main.ts build web

FROM nginx:1.27-alpine
COPY ${join(at, DIR, "nginx.conf")} /etc/nginx/conf.d/default.conf
${layout.site ? `COPY ${join(at, layout.site)} /usr/share/nginx/html
` : ""}COPY --from=build ${join("/app", at, out)} ${join("/usr/share/nginx/html", layout.gamePath)}
EXPOSE 80
`,
    "Dockerfile.relay": `# Netplay relay for ${config.name}: dotframe relay serve. Generated by dotframe deploy init.
FROM oven/bun:${v.bun}-alpine
WORKDIR /app
# The dotframe version the game has installed; bump it together with the game's.
RUN bun add dotframe@${v.dotframe}
ENV PORT=8787
EXPOSE 8787
CMD ["bun", "node_modules/dotframe/cli/main.ts", "relay", "serve"]
`,
    "nginx.conf": nginx(layout),
    "compose.yaml": `# ${config.name}: the game at / and the netplay relay at /relay on the same host. In Dokploy, point the domain's
# / at service web (port 80) and /relay at service relay (port 8787).
services:
  web:
    build:
      context: ${context}
      dockerfile: ${join(at, DIR, "Dockerfile.web")}
    restart: unless-stopped
    expose:
      - "80"
  relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    restart: unless-stopped
    environment:
      PORT: "8787"
    expose:
      - "8787"
`,
    ".dockerignore": "**/node_modules\n**/dist\n**/.dotframe\n.git\n",
  };
}

function nginx(layout: Layout): string {
  const sub = layout.gamePath !== "/";
  const base = layout.gamePath.replace(/\/$/, "");
  return `server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;
  # Bundles are content-hashed; HTML must never be cached (Discord caches aggressively).
  location ~ \\.html$ { add_header Cache-Control "no-cache"; }
${sub ? `  location = ${base} { return 301 ${base}/$is_args$args; }
  location ${base}/ { try_files $uri $uri/ ${base}/index.html; }
` : ""}  location / { try_files $uri $uri/ /index.html; }
  location ~* \\.(png|mp3|js|json|css|woff2|webp|jpg|ico)$ { expires 7d; add_header Cache-Control "public"; }
}
`;
}

export async function deployInit(ctx: Ctx, name: string | undefined, provider: string | undefined, compose: string | undefined, site?: string, path?: string): Promise<void> {
  if (!name) throw new CliError("MISSING_ARG", "deploy init needs a target", "dotframe deploy init web --provider dokploy", "export-web");
  if (provider !== "dokploy") throw new CliError("UNSUPPORTED", `deploy init supports --provider dokploy (got ${provider ?? "none"}); vercel needs no files`, "dotframe deploy init web --provider dokploy", "export-web");
  const config = loadConfig();
  const t = target(config, name);
  if (!t.out) throw new CliError("NO_OUT", `target "${name}" needs an out dir`, "", "export-web");
  const repo = await gitRoot(ctx, config.root);
  const game = relative(repo, config.root);
  // compose.yaml sits in <game>/deploy; the web build context is the repo root, so workspace code is visible.
  if (site && !existsSync(join(config.root, site))) throw new CliError("BAD_ARG", `--site ${site} does not exist under the game root`, "pass a folder with an index.html, relative to the game root", "export-web");
  const gamePath = path ? `/${path.replace(/^\/+|\/+$/g, "")}/`.replace("//", "/") : site ? "/play/" : "/";
  const generated = files(config, game, t.out, relative(join(config.root, DIR), repo) || ".", versions(config.root, repo), { site, gamePath });
  const dir = join(config.root, DIR);
  const written = Object.keys(generated).map((f: string): string => join(DIR, f));
  const existing = written.filter((f: string): boolean => existsSync(join(config.root, f)));
  if (ctx.dryRun) {
    print(ctx, { dryRun: true, files: written, existing }, (): string => `would write ${written.join(", ")}${existing.length ? ` (overwrites ${existing.join(", ")})` : ""}`);
    return;
  }
  if (existing.length > 0 && !ctx.yes) throw new CliError("EXISTS", `${existing.join(", ")} already exist`, "rerun with --yes to overwrite, or edit them by hand", "export-web");
  mkdirSync(dir, { recursive: true });
  for (const [f, text] of Object.entries(generated)) writeFileSync(join(dir, f), text);
  // The repo-root .dockerignore is the one docker reads for a repo-root context.
  if (!existsSync(join(repo, ".dockerignore"))) writeFileSync(join(repo, ".dockerignore"), generated[".dockerignore"]);
  const raw = JSON.parse(readFileSync(join(config.root, CONFIG_FILE), "utf8")) as { targets: Record<string, { deploy?: unknown }> };
  raw.targets[name].deploy = { provider: "dokploy", compose: compose ?? "", dir: DIR, ...(site ? { site } : {}), ...(gamePath !== "/" ? { path: gamePath } : {}) };
  writeFileSync(join(config.root, CONFIG_FILE), `${formatJson(raw)}\n`);
  print(ctx, { files: written, next: ["git add deploy dotframe.json && git commit && git push", "create the compose in Dokploy from this repo (compose path below)", `dotframe config set targets.${name}.deploy.compose '"<compose id>"'`] }, (): string =>
    [`wrote ${written.join(", ")}`, `compose path for Dokploy: ${join(game, DIR, "compose.yaml")}`, `then: dotframe config set targets.${name}.deploy.compose '"<compose id>"' and dotframe deploy ${name}`].join("\n"),
  );
}

interface Deployment {
  id: string;
  status: string;
  created: string;
}

async function vpsJson<T>(ctx: Ctx, root: string, args: string[]): Promise<T> {
  const r = await exec({ ...ctx, json: true }, root, { label: `vps ${args.join(" ")}`, argv: ["vps", ...args, "--json"] });
  if (r.code !== 0) throw new CliError("DEPLOY_FAILED", r.tail, "vps doctor; check the profile and API key", "export-web");
  return JSON.parse(r.output) as T;
}

export async function deployDokploy(ctx: Ctx, config: Config, name: string, compose: string): Promise<void> {
  const skill = "export-web";
  if (!compose) throw new CliError("CONFIG_PLACEHOLDER", `targets.${name}.deploy.compose is empty`, `dotframe config set targets.${name}.deploy.compose '"<compose id>"' (vps compose list)`, skill);
  for (const f of ["compose.yaml", "Dockerfile.web", "nginx.conf"]) {
    if (!existsSync(join(config.root, DIR, f))) throw new CliError("NOT_BUILT", `${DIR}/${f} is missing`, `dotframe deploy init ${name} --provider dokploy`, skill);
  }
  // Dokploy builds what is on the remote branch, not this working tree.
  const status = await exec({ ...ctx, json: true }, config.root, { label: "git status", argv: ["git", "status", "--porcelain", "--branch"] });
  const unpushed = /\[ahead \d+/.test(status.output.split("\n")[0] ?? "");
  const dirty = status.output.split("\n").slice(1).some((l: string): boolean => l.trim() !== "");
  const plan = { target: name, provider: "dokploy", compose, command: `vps -y compose redeploy ${compose}`, unpushedCommits: unpushed, uncommittedChanges: dirty };
  if (ctx.dryRun) {
    print(ctx, { dryRun: true, ...plan }, (): string =>
      [`would redeploy compose ${compose} from the remote branch`, unpushed ? "warning: local commits are not pushed; Dokploy will not see them" : "", dirty ? "warning: uncommitted changes will not deploy" : ""].filter(Boolean).join("\n"),
    );
    return;
  }
  gate(ctx, `deploy ${name} to Dokploy`, skill);
  if (!which("vps")) throw new CliError("TOOL_MISSING", "vps CLI not found", "install crafter-station/vps-cli and log in", skill);
  const before = await vpsJson<Deployment[]>(ctx, config.root, ["compose", "deployments", compose]);
  const known = new Set(before.map((d: Deployment): string => d.id));
  const started = await exec({ ...ctx, json: true }, config.root, { label: "vps redeploy", argv: ["vps", "-y", "compose", "redeploy", compose, "--json"] });
  if (started.code !== 0) throw new CliError("DEPLOY_FAILED", started.tail, "", skill);
  if (!ctx.json) console.error("> waiting for the Dokploy deployment");
  // Wait for the new deployment to reach a terminal state; a build failure carries its log.
  for (;;) {
    await Bun.sleep(5000);
    const now = await vpsJson<Deployment[]>(ctx, config.root, ["compose", "deployments", compose]);
    const fresh = now.find((d: Deployment): boolean => !known.has(d.id));
    if (!fresh || fresh.status === "running" || fresh.status === "queued") continue;
    if (fresh.status === "done") {
      print(ctx, { ...plan, deployment: fresh.id, status: fresh.status }, (): string => `deployed: compose ${compose}, deployment ${fresh.id}`);
      return;
    }
    const logs = await vpsJson<{ log: string }>(ctx, config.root, ["compose", "logs", compose, "--deployment", fresh.id, "--tail", "60"]);
    const logDir = join(config.root, ".dotframe", "logs");
    mkdirSync(logDir, { recursive: true });
    const log = join(logDir, `deploy-${name}.log`);
    writeFileSync(log, logs.log);
    throw new CliError("DEPLOY_FAILED", `Dokploy deployment ${fresh.id} ended ${fresh.status}:\n${logs.log.split("\n").slice(-15).join("\n")}`, `read ${log}; reproduce with dotframe doctor --docker`, skill, 1, log);
  }
}

// Builds the web image locally: what Dokploy would run, minus the network round trip.
export async function dockerCheck(ctx: Ctx, config: Config): Promise<{ check: string; ok: boolean; detail: string; fix: string; skill: string }> {
  const base = { check: "docker:web", skill: "export-web" };
  const dockerfile = join(config.root, DIR, "Dockerfile.web");
  if (!existsSync(dockerfile)) return { ...base, ok: false, detail: `${DIR}/Dockerfile.web is missing`, fix: "dotframe deploy init web --provider dokploy" };
  if (!which("docker")) return { ...base, ok: false, detail: "docker not found", fix: "install Docker Desktop or OrbStack" };
  const repo = await gitRoot(ctx, config.root);
  const r = await exec({ ...ctx, json: true }, repo, { label: "docker build", argv: ["docker", "build", "-f", dockerfile, "-t", `${config.name}-web:check`, "."] });
  if (r.code === 0) return { ...base, ok: true, detail: `${DIR}/Dockerfile.web builds`, fix: "" };
  const logDir = join(config.root, ".dotframe", "logs");
  mkdirSync(logDir, { recursive: true });
  writeFileSync(join(logDir, "docker-web.log"), r.output);
  const cause = r.output.split("\n").filter((l: string): boolean => /error|not found/i.test(l)).slice(-3).join(" | ");
  return { ...base, ok: false, detail: `docker build failed: ${cause || "see log"}`, fix: `read ${join(".dotframe", "logs", "docker-web.log")}; missing binaries go in "requires" in dotframe.json` };
}
