// Generates what a scriptc library-mode host needs from an app spec and native/ffi.<target>.json:
//   <out>/<name>.profile.json  library profile: the app's exports plus every df* function as a callback channel
//   <out>/<name>_glue.c         C trampolines (scriptc calls callbacks as fn(ctx, args...)) and a registration function
// Usage: bun tools/gen-library-glue.ts <app.json> <out-dir> [ffi manifest]
// app.json: { "name": "smash", "entry": "app.ts" (relative to app.json), "exports": [{ "export": "frame", "params": ["f64"], "returns": "bool" }] }
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

interface ManifestFunction {
  name: string;
  symbol: string;
  params: string[];
  returns: string;
}

interface AppExport {
  export: string;
  params: string[];
  returns: string;
}

interface AppSpec {
  name: string;
  entry: string;
  exports: AppExport[];
}

const [appPath, outDir, manifestPath = join(import.meta.dir, "..", "native", "ffi.macos.json")] = process.argv.slice(2);
const app = JSON.parse(readFileSync(appPath, "utf8")) as AppSpec;
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as { functions: ManifestFunction[] };

// Profile callbacks accept scalars and borrowed string/bytes parameters, and return scalars or void.
const CALLBACK_PARAMS = new Set(["f64", "bool", "u8", "u32", "i32", "string", "bytes"]);
const CALLBACK_RETURNS = new Set(["f64", "bool", "u8", "u32", "i32", "void"]);
// The host drives the event loop and shutdown itself, so these stay out of the 32-channel callback budget.
const HOST_OWNED = new Set(["dfPoll", "dfClose"]);
const usable = manifest.functions.filter(
  (f) => !HOST_OWNED.has(f.name) && f.params.every((p) => CALLBACK_PARAMS.has(p)) && CALLBACK_RETURNS.has(f.returns),
);
const skipped = manifest.functions.filter((f) => !usable.includes(f) && !HOST_OWNED.has(f.name)).map((f) => f.name);

const cType: Record<string, string> = { f64: "double", bool: "uint8_t", u8: "uint8_t", u32: "uint32_t", i32: "int32_t", void: "void" };
const cParams = (params: string[]): string[] =>
  params.flatMap((p, i) => (p === "string" || p === "bytes" ? [`const uint8_t *a${i}`, `size_t a${i}_len`] : [`${cType[p]} a${i}`]));
const cArgs = (params: string[]): string[] => params.flatMap((p, i) => (p === "string" || p === "bytes" ? [`a${i}`, `a${i}_len`] : [`a${i}`]));

const prefix = `${app.name}_`;
const profile = {
  profile_format: 1,
  name: app.name,
  entry: resolve(dirname(appPath), app.entry),
  emission: "llvm",
  abi: {
    prefix,
    init_symbol: `${prefix}runtime_init`,
    sink_register_symbol: `${prefix}sink`,
    callback_register_symbol: `${prefix}callback`,
  },
  callbacks: usable.map((f) => ({ name: f.name, params: f.params, returns: f.returns })),
  exports: app.exports.map((e) => ({ export: e.export, symbol: `${prefix}${e.export}`, params: e.params, returns: e.returns })),
};

let glue = `// Generated by dotframe tools/gen-library-glue.ts. Connects ${app.name}'s library callbacks to the dotframe native shim.
#include <stddef.h>
#include <stdint.h>

int32_t ${prefix}callback(const char *name, void *fn, void *ctx);
`;
for (const f of usable) glue += `${cType[f.returns]} ${f.symbol}(${cParams(f.params).join(", ") || "void"});\n`;
glue += "\n";
for (const f of usable) {
  const params = ["void *ctx", ...cParams(f.params)].join(", ");
  const call = `${f.symbol}(${cArgs(f.params).join(", ")})`;
  glue += `static ${cType[f.returns]} cb_${f.name}(${params}) {\n  (void)ctx;\n  ${f.returns === "void" ? `${call};` : `return ${call};`}\n}\n\n`;
}
glue += `// Registers every callback; returns the number that failed to register (0 on success).\nint32_t ${prefix}register_callbacks(void) {\n  int32_t failed = 0;\n`;
for (const f of usable) glue += `  if (${prefix}callback("${f.name}", (void *)cb_${f.name}, NULL) != 0) failed += 1;\n`;
glue += "  return failed;\n}\n";

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, `${app.name}.profile.json`), `${JSON.stringify(profile, null, 2)}\n`);
writeFileSync(join(outDir, `${app.name}_glue.c`), glue);
console.log(`${usable.length} callbacks${skipped.length ? `, skipped (unsupported in library mode): ${skipped.join(", ")}` : ""}`);
